# Generated by Django 5.2 on 2025-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=False, null=True, upload_to='img_media/'),
        ),
    ]
