# Generated by Django 5.2 on 2025-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_size_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, max_length=250, null=True, upload_to='main_image.jpeg/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='img_media/'),
        ),
    ]
