# Generated by Django 5.2 on 2025-11-10 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='User',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='ALL', max_length=5),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
